### ISSUE TITLE
unimplemented! breaks Servo unexpectedly

### ISSUE THREAD

**Issue by jdm** [netvl/immeta#5]
Servo is relying on immeta to retrieve metadata about images when performing layout but the complete image data is not yet available. Blocks like https://github.com/netvl/immeta/blob/f252cf4a154e0e110f96bf3cf7392e6b23366e21/src/formats/webp.rs#L66 cause us difficulty; an `Err` return value would be much nicer for us.

**Comment by netvl** [comment]
Sorry! Indeed, Webp parser is not complete yet, I shouldn't have added it to the autoload sequence. I will change this to an error when I will be able to (probably in a few hours).

**Comment by netvl** [comment]
Fixed in 07772dab3a8307c195259c8c7a1ec6b11180fb65

**Comment by netvl** [comment]
Please use v0.3.1 now.

**Comment by jdm** [comment]
Thanks!
